export const getSampleResumeData = () => ({
  firstName: "Kiran",
  middleName: "Atmaram",
  lastName: "Aher",
  designation: "Executive Frontend Developer",
  email: "kiranaher5171@gmail.com",
  phone: "+91 7264965171",
  address: "Deola",
  city: "Nashik",
  state: "Maharashtra",
  zipCode: "",
  country: "India",
  linkedIn: "https://linkedin.com/in/kiran-aher",
  portfolio: "",
  github: "https://github.com/kiranaher5171",
  professionalSummary:
    "Experienced Executive Frontend Developer with expertise in React JS, Material-UI, and responsive web design. Proven track record of creating 20+ responsive interfaces and 15+ interactive applications. Skilled in optimizing application performance, achieving up to 30% improvement in page load speed. Strong background in cross-browser compatibility, mobile-first design, and modern JavaScript ES6+ features.",
  workExperience: [
    {
      jobTitle: "Executive Frontend Developer (UI) [React]",
      company: "Decimal Point Analytics",
      startDate: "2023-08",
      endDate: "",
      location: "Nashik, Maharashtra",
      description:
        "Created over 20 responsive interfaces using HTML, CSS, and Bootstrap, ensuring cross-browser compatibility for a consistent user experience across different platforms.\nDeveloped 15+ interactive applications with React JS and Material-UI, focusing on creating reusable components and efficient state management.\nTranslated 10+ mockups into precise web designs, collaborating closely with web designers to meet client expectations and align with design standards.\nManaged weekly code reviews and PR merging, updating, removing, and replacing packages while using Sonar scans to fix over 50 high vulnerabilities and bugs.\nOptimized application performance, achieving up to a 30% improvement in page load speed to enhance the overall user experience.\nBuilt 20+ mobile-first, responsive designs using media queries and Bootstrap's grid system, ensuring smooth adaptation across various devices and screen sizes.\nUtilized HTML5 and CSS3 for semantic structure and accessibility, incorporating Flexbox and CSS Grid for complex layouts in over 50 project components.\nApplied JavaScript ES6+ features and React hooks like useState and useEffect in all components, enhancing interactivity and effective state management.\nCustomized 10+ Material-UI themes and components for a consistent look and feel, adjusting styling to meet specific branding and UI requirements.\nConducted extensive cross-browser and cross-device testing on all deployed projects, resolving layout and functionality issues to achieve compatibility and a seamless user experience.",
    },
    {
      jobTitle: "Frontend Developer Intern",
      company: "Manasvi Tech Solution Pvt Ltd",
      startDate: "2023-03",
      endDate: "2023-08",
      location: "Nashik, Maharashtra",
      description:
        "Contributed as a team member to resolve code issues and enhance skills in creating responsive designs, ensuring consistency across projects.\nParticipated in workshops and training sessions to expand knowledge in front-end technologies and stay updated with industry trends, improving overall work quality.\nAwarded 'Intern of the Month' for consistently exceeding project deadlines and delivering high-quality work.",
    },
  ],
  education: [
    {
      degree: "Bachelor of Computer Science",
      field: "Computer Science",
      institution: "ACS College Kalwan",
      location: "Nashik, Maharashtra",
      startDate: "2018",
      endDate: "2021",
      gpa: "A",
      summary: "Graduated with Grade A. Served as a volunteer for the National Service Scheme (NSS) for a tenure of 3 years.",
    },
    {
      degree: "HSC (Higher Secondary Certificate)",
      field: "",
      institution: "KKW Junior College Niphad",
      location: "Nashik, Maharashtra",
      startDate: "2016",
      endDate: "2018",
      gpa: "A",
      summary: "Completed Higher Secondary Education with Grade A.",
    },
  ],
  skills: [
    "HTML",
    "CSS",
    "JavaScript",
    "Responsive Design",
    "Cross-Browser Compatibility",
    "React JS",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "GitHub",
    "Bitbucket",
    "Problem Solving",
    "Leadership",
    "Teamwork",
    "Communication Skills",
    "Front End Development",
    "MERN Stack",
    "Web Development",
    "Best Practices of Software Engineering",
  ],
  certifications: [
    {
      name: "React - The Complete Guide",
      organization: "Udemy",
      issueDate: "2023-05",
      expirationDate: "",
      credentialId: "UDEMY-REACT-2023",
      summary: "Comprehensive React.js course covering hooks, context API, Redux, and advanced patterns. Completed hands-on projects including e-commerce applications and real-time chat systems.",
    },
    {
      name: "JavaScript Algorithms and Data Structures",
      organization: "freeCodeCamp",
      issueDate: "2022-11",
      expirationDate: "",
      credentialId: "FCC-JS-ALGO-2022",
      summary: "Mastered JavaScript fundamentals, ES6+ features, and data structures. Completed 300+ coding challenges covering algorithms, object-oriented programming, and functional programming.",
    },
    {
      name: "Responsive Web Design",
      organization: "freeCodeCamp",
      issueDate: "2022-08",
      expirationDate: "",
      credentialId: "FCC-RWD-2022",
      summary: "Certified in creating responsive web designs using HTML5, CSS3, Flexbox, and CSS Grid. Built multiple responsive projects demonstrating mobile-first design principles.",
    },
  ],
  projects: [
    {
      name: "E-Commerce Dashboard",
      url: "https://github.com/kiranaher5171/ecommerce-dashboard",
      technologies: "React, Material-UI, Redux, Chart.js, REST API",
      date: "2023-10",
      description:
        "Developed a comprehensive e-commerce admin dashboard with real-time analytics, order management, and inventory tracking. Implemented responsive design with Material-UI components and integrated Chart.js for data visualization. Features include user authentication, role-based access control, and export functionality.",
    },
    {
      name: "Task Management Application",
      url: "https://github.com/kiranaher5171/task-manager",
      technologies: "React, Bootstrap, LocalStorage API, Context API",
      date: "2023-07",
      description:
        "Built a full-featured task management application with drag-and-drop functionality, task categorization, priority management, and deadline tracking. Implemented local storage for data persistence and responsive design for mobile and desktop devices.",
    },
    {
      name: "Weather Forecast App",
      url: "https://github.com/kiranaher5171/weather-app",
      technologies: "React, OpenWeatherMap API, Tailwind CSS, Axios",
      date: "2023-04",
      description:
        "Created a responsive weather application displaying current conditions and 7-day forecasts. Integrated OpenWeatherMap API for real-time data, implemented location-based search, and added weather icons with smooth animations using Tailwind CSS.",
    },
    {
      name: "Portfolio Website",
      url: "https://kiranaher.dev",
      technologies: "React, Next.js, Framer Motion, CSS3",
      date: "2023-02",
      description:
        "Designed and developed a modern, responsive portfolio website showcasing projects and skills. Implemented smooth animations using Framer Motion, optimized for SEO with Next.js, and achieved 95+ Lighthouse performance score.",
    },
  ],
  languages: [
    "English (Professional)",
    "Hindi (Native)",
    "Marathi (Native)"
  ],
});
